require("ankit.plugins-setup")
require("ankit.core.colorscheme")
require("ankit.core.options")
require("ankit.core.keymaps")
require("ankit.plugins.comment")
require("ankit.plugins.nvim-tree")
require("ankit.plugins.lualine")
require("ankit.plugins.telescope")
require("ankit.plugins.nvim-cmp")
require("ankit.plugins.lsp.mason")
-- require("ankit.plugins.lsp.lspsaga")
require("ankit.plugins.lsp.lspconfig")
require("ankit.plugins.lsp.null-ls")
require("ankit.plugins.autopairs")
require("ankit.plugins.treesitter")
require("ankit.plugins.gitsigns")
require("ankit.plugins.bufferline")
require("ankit.plugins.neoscroll")
require("ankit.plugins.nvim-colorizer")
-- require("ankit.plugins.alpha-nvim")
-- require("ankit.plugins.notify")
require("ankit.plugins.toggleterm-nvim")
require("ankit.plugins.scrollbar")
require("ankit.plugins.dashboard")
require("ankit.plugins.neogit")
require("ankit.plugins.aerial")
require("ankit.plugins.refactoring")
require("ankit.plugins.impatient")
require("ankit.plugins.outline")
require("ankit.plugins.legendary")
require("ankit.plugins.indent-blankline")
require("ankit.plugins.navic")
-- require("ankit.plugins.wilder")
-- require("ankit.plugins.mini")               NOTE: animates the nvim (few bad animation exist)
-- require("ankit.plugins.material_icon")
-- require("ankit.plugins.rainbow") -- uncomment this line if you want rainbow colorized brackets
